apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: acs-enterprise-contract-custom-tasks
  labels:
    test.appstudio.openshift.io/optional: "true"
spec:
  application: acs
  contexts:
  - description: Application testing
    name: application
  params:
  - name: POLICY_CONFIGURATION
    value: github.com/stackrox/stackrox//.tekton/enterprise-contract?ref=rhtap-allow-quay-registry
  resolverRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract-redhat-no-hermetic.yaml
    resolver: git
