# Originally defined in https://github.com/release-engineering/rhtap-ec-policy/blob/main/data/rule_data.yml#L4-L8.
rule_data_custom:
  allowed_registry_prefixes:
  - registry.access.redhat.com/
  - registry.redhat.io/
  - brew.registry.redhat.io/rh-osbs/openshift-golang-builder
  # TODO(ROX-18380): Remove eBPF probes for kernel drivers
  - brew.registry.redhat.io/rh-osbs/rhacs-drivers-build-rhel8
