# Reduced resource overrides for the stackrox-central-services Helm chart that allow deploying
# on Docker for Desktop on a typical developer box.

central:
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  db:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 700m
        memory: 2Gi
  telemetry:
    enabled: false

scanner:
  replicas: 1
  autoscaling:
    disable: true
  resources:
    requests:
      cpu: "300m"
      memory: "500Mi"
    limits:
      cpu: 1
      memory: "2Gi"
  dbResources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: 1
      memory: "1Gi"
scannerV4:
  matcher:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 3
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  indexer:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 3
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  db:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "500Gi"
