apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gke-qa-e2e-tests-pipeline
  labels:
    build.appstudio.redhat.com/pipeline: "gke-qa-e2e-tests"
spec:
  params:
    - name: CLUSTER_NAME
      type: string
      description: Name of the infra cluster
      default: "konflux-gke-qa-e2e-tests"
    - name: INFRA_TOKEN_SECRET_NAME
      type: string
      description: Secret containing the INFRA_TOKEN.
      default: "e2e-infra-token-secret"
  tasks:
  - name: install-infractl
    description: Install infractl
    params:
      - name: CLUSTER_NAME
        value: "$(params.CLUSTER_NAME)"
      - name: INFRA_TOKEN_SECRET_NAME
        value: "$(params.INFRA_TOKEN_SECRET_NAME)"
    taskSpec:
      volumes:
      - name: infra-token-secret
        secret:
          secretName: $(params.INFRA_TOKEN_SECRET_NAME)
          optional: true
      steps:
      - image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69
        volumeMounts:
          - name: infra-token-secret
            mountPath: /infra-token-secret
        script: |
          mkdir -p /usr/local/bin
          curl --fail -sL https://infra.rox.systems/v1/cli/linux/amd64/upgrade \
          | jq -r ".result.fileChunk" \
          | base64 -d \
          > /usr/local/bin/infractl
          chmod +x /usr/local/bin/infractl
          infractl --version

          export INFRA_TOKEN=$(</infra-token-secret/infra-token)

          echo ${INFRA_TOKEN} | wc

          infractl create "${CLUSTER_NAME}" --wait --no-slack

          infractl artifacts ${CLUSTER_NAME}"
