apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/olm-operator-konflux-sample?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "master" && 
      (".tekton/single-arch-build-pipeline.yaml".pathChanged() || 
      ".tekton/operator-bundle-pull-request.yaml".pathChanged() || 
      ".tekton/operator-bundle-push.yaml".pathChanged() || 
      "operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: olm-operator
    appstudio.openshift.io/component: operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: operator-bundle-on-push
  namespace: rh-acs-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/rhacs-eng/stackrox-operator-bundle:on-pr-{{revision}}
  - name: dockerfile
    value: operator/bundle.Dockerfile
  # TODO(ROX-20234): Enable hermetic builds
  # Do not use hermetic for now as we are going to generate our manifest at build time. We need to pull in content.
  - name: hermetic
    value: "false"
  pipelineRef:
    name: operator-bundle-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'