name: Batch load test metrics
on:
  workflow_dispatch:
  schedule:
  - cron: 23 * * * *

# Ensure that only a single batch loader is running
concurrency: Batch load test metrics

jobs:
  batch-load-test-metrics:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69-12-g470b9f23c1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Load
      env:
        GCP_SERVICE_ACCOUNT_STACKROX_CI: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
      shell: bash
      run: |
        source scripts/ci/lib.sh

        setup_gcp
        batch_load_test_metrics
