name: Scanner dev vulnerability update
on:
  schedule:
  - cron: "30 */4 * * *"
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: "Choose the NVD source"
        options:
        - nvd-api
        - nvd-feeds
        required: true
        default: nvd-api

jobs:
  parse-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Parse VULNERABILITY_BUNDLE_VERSION
      id: set-versions
      run: |
        versions=$(grep -v '^#' scanner/updater/version/VULNERABILITY_BUNDLE_VERSION | awk -F, '{print $1 "|" $2}' | paste -sd "," -)
        versions_json="[\"${versions//,/\",\"}\"]"
        echo "Versions JSON: ${versions_json}"
        echo "versions=${versions_json}" >> "$GITHUB_OUTPUT"

  prepare-environment:
    needs: parse-versions
    runs-on: ubuntu-latest
    outputs:
      manual_url: ${{ steps.set-manual-url.outputs.manual_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download NVD
      run: |
        set -eu
        since_time=$(date -u -d '24 hours ago' '+%a, %d %b %Y %H:%M:%S GMT')
        if [ "${{ github.event.inputs.job || 'nvd-api' }}" = "nvd-api" ]; then
          url="https://definitions.stackrox.io/v4/nvd/nvd-api.zip"
        else
          url="https://definitions.stackrox.io/v4/nvd/nvd-feeds.zip"
        fi

        code=$(curl \
            -o nvd.zip \
            -w "%{http_code}" \
            -H "If-Modified-Since: $since_time" \
            "$url")

        echo "code: $code"
        echo "$code" | grep -q 200

    - name: Set MANUAL_URL
      id: set-manual-url
      run: |
        if [ "${{ github.event_name }}" == "schedule" ]; then
          echo "MANUAL_URL=https://raw.githubusercontent.com/stackrox/stackrox/master/scanner/updater/manual/vulns.yaml" >> "$GITHUB_ENV"
        else
          echo "MANUAL_URL=https://raw.githubusercontent.com/stackrox/stackrox/${{ github.event.pull_request.head.sha }}/scanner/updater/manual/vulns.yaml" >> "$GITHUB_ENV"
        fi

    - uses: ./.github/actions/upload-artifact-with-retry
      with:
        name: nvd
        path: nvd.zip
        if-no-files-found: error

  build-and-upload:
    needs:
    - parse-versions
    - prepare-environment
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69
      volumes:
      # The updater makes heavy use of /tmp files.
      - /tmp:/tmp
      - /usr:/mnt/usr
      - /opt:/mnt/opt
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        vb: ${{ fromJson(needs.parse-versions.outputs.versions) }}
    steps:
    - name: Split version and branch
      id: split
      run: |
        IFS="|" read -r version branch <<< "${{ matrix.vb }}"
        echo "version=${version}" >> "$GITHUB_OUTPUT"
        echo "branch=${branch}" >> "$GITHUB_OUTPUT"

    - name: Free up disk space
      shell: bash
      run: |
        set +e
        set -x
        df -h
        for delete in /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL; do
          rm -rf "/mnt${delete:?}"
        done
        df -h

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ steps.split.outputs.branch }}

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Build updater
      run: |
        echo "Building updater for version ${{ steps.split.outputs.version }} on branch ${{ steps.split.outputs.branch }}..."
        make tag
        make -C scanner bin/updater

    - name: Upload Updater Artifact
      uses: actions/upload-artifact@v4
      with:
        name: updater-${{ steps.split.outputs.version }}
        path: scanner/bin/updater
        if-no-files-found: error

    - name: Download NVD
      uses: ./.github/actions/download-artifact-with-retry
      with:
        name: nvd
        path: nvd.zip

    - name: Set Updater
      run: |
        chmod +x scanner/bin/updater
        mkdir vulns

    - name: Run Updater (single bundle)
      env:
        STACKROX_NVD_ZIP_PATH: nvd.zip
      run: scanner/bin/updater export vulns --manual-url "${{ needs.prepare-environment.outputs.manual_url }}"

    - name: Run updater (multi bundle)
      env:
        STACKROX_NVD_ZIP_PATH: nvd.zip
      run: |
        echo "Running multi-bundle updater for version ${{ steps.split.outputs.version }} with manual URL ${{ needs.prepare-environment.outputs.manual_url }}..."
        scanner/bin/updater export --manual-url "${{ needs.prepare-environment.outputs.manual_url }}" --split bundles
        zip vulns/vulnerabilities.zip bundles/*.json.zst
